Working register and login with JWT token and password encryption in database.
cami2803/BalanceBuddy-Lifestyle-Application pull request #1
Opened 2024-07-23 14:51 UTC by cami2803

Implemented functionality to register and to login with a JWT token using OAuth. The password in the database is encrypted using JWT Encoder.

2024-07-24 07:45 UTC, PatrickDiallo23 requested changes
Have a look at the comments, please.

2024-07-24 07:45 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/config/SecurityConfiguration.java
Did you also handle the scenario where token is expired? If not, please add the logic for this kind of scenario (if the token is expired, then logout the user).

If you want to cover this class in the Unit Testing, you could use Constructor Injection. Please refer to [this](https://stackoverflow.com/questions/40620000/spring-autowired-on-properties-vs-constructor).

You don't use logs in this class, you can delete @Slf4j. You have any unused imports in the codebase, please delete the imports.

2024-07-24 07:45 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/controllers/UserController.java
You could implement in the UserService the _findById_ method so that you could get rid of UserRepository class.

Replace orElseThrow() with orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "User not found")) to provide a more meaningful HTTP response.

Be careful to not expose the user id in the URL path. If so, please provide an additional secure way for user retrieval.

I think that _user_ method was supposed to be _getUser_.

2024-07-24 15:54 UTC, PatrickDiallo23 requested changes

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/repositories/UserRepository.java
You can keep the UserRepository so that you will have the controller, service and repository layers. What I meant by getting rid by UserRepository was that it wasn't necessary to have the UserRepository class in the UserController class, because you would have the UserRepository in the UserService class (where you implement the logic for the communication with the database).

In the Controller class you just call the methods defined in the Service class, and in the Service class you implement the business logic and database communication (with the help of Repository class).

**Note:** Do the above change if you still want to use UseRepository class. I saw that you opted for EntityManager class. If you don't need the UseRepository class, then you can ignore this comment.

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/config/JWTToUserConvertor.java
> +// presentation of a username and a password
You don't need to explain in detail what a method does. You can just leave: "Converts a JWT into UsernamePasswordAuthenticationToken". Try to keep it simple and give some hints. Other devs should know how things work in detail.

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/config/JWTToUserConvertor.java
> +    // to authenticate the user in the application
Same for this comment. You can just write a short summary of what this methods does/returns based on some JWT token.

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/config/KeyUtils.java
>      private String refreshTokenPublicKeyPath;
In this case is clear that these variables are representing some paths for the keys. You can delete the comments. The role of the comments is to explain pieces or sequences of code that don't seem very clear or intuitive at first glance, such as a more complex business logic function.

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/config/KeyUtils.java
> +                // can be encrypted by anyone, via the public key, but can only be decrypted by someone who knows the private key)
Just leave "Initialize a KeyFactory for the RSA algorithm". You don't have to explain this in detail especially as they can google the RSA algorithm.

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/config/KeyUtils.java
> +    // Retrieves private key for refresh tokens
It is not needed to explain the getters.

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/config/PasswordEncoderConfiguration.java
> +    // call will have a different result, therefore the password needs to be encoded only once.
You can leave in the comments "BCrypt is used for hashing the password" or no comments at all because it is a well known password-hashing technique.

2024-07-24 15:54 UTC, PatrickDiallo23 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/controllers/UserController.java
> +    // id does not appear in the request url
You don't need to mention that id does not appear in the request url because this can be seen in the @GetMapping annotation's value.

2024-07-25 08:44 UTC, cami2803 commented on backend/BalanceBuddy/src/main/java/com/example/balancebuddy/repositories/UserRepository.java
I will use EntityManager for this project, without having a separate package for repositories.

2024-07-25 10:36 UTC, PatrickDiallo23 approved these changes
Looks good to me.

2024-07-25 14:24 UTC, merged